project_id = "gesvuirjinwcdwfuavod"

[functions.delete-account]
verify_jwt = true

[functions.send-support-ticket]
verify_jwt = true

[functions.generate-testimonials]
verify_jwt = false

[functions.generate-image]
verify_jwt = false
